#Arquivo de configuração para CI/CD - Travis CI
#A tag matrix é utilizado para que seja configurado multiplo build/deploy - ANDROID/IOS

matrix:
  include:
    - os: linux
      language: android
      dist: trusty
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

      # ANDROID BUILD
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - sys-img-armeabi-v7a-google_apis-28
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid

      # HABILITAR LICENÇA ANDROID GRADLEW
      before_script:
        - yes | sdkmanager --update
        - ls -la
        - chmod +x /home/travis/build/maikejo/helpvet-flutter/android/gradlew
      script:
        # EXECUTA SCRIPT PARA BUILD DO APPBUNDLE RELEASE
        - flutter build appbundle --build-number=$TRAVIS_BUILD_NUMBER --release
        - gem install bundler && cd android && bundle install && cd ..
        - cd android
        # EXECUTA LANE PARA DEPLOY NO GOOGLE PLAY
        - bundle exec fastlane beta
install:
  # INSTALA SDK FLUTTER - V2.17
  - git clone -b '1.22.1+hotfix.8' --depth 1 https://github.com/flutter/flutter.git
  - export PATH="$PATH:`pwd`/flutter/bin"
cache:
  directories:
    - $HOME/.pub-cache