language: generic

env:
  - VERSION_CODE_BASE=1908191509 FLUTTER_BUILD_RELEASE_CHANNEL=beta

branches:
  only:
    - master

matrix:
  include:
    - name: Android Build
      language: android
      jdk: openjdk8

      before_script:
        #- openssl aes-256-cbc -K $encrypted_d0cc22ff5b43_key -iv $encrypted_d0cc22ff5b43_iv -in secrets.tar.enc -out secrets.tar -d
        #- tar xvf secrets.tar
        - ANDROID_COMPILE_SDK=28
        - ANDROID_BUILD_TOOLS=28.0.1
        - ANDROID_SDK_TOOLS=4333796
        # Install android tools
        - export ANDROID_HOME=$HOME/android-sdk-linux
        - wget -q https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_SDK_TOOLS.zip -O android-sdk-tools.zip
        - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
        - rm android-sdk-tools.zip
        - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
        # Silence warning.
        - mkdir -p ~/.android
        - touch ~/.android/repositories.cfg
        - gem install bundler && cd android && bundle install && cd ..

      install:
        - sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null
        # install flutter
        - FLUTTER_CHANNEL=stable
        - FLUTTER_VERSION=1.0.0-${FLUTTER_CHANNEL}
        - wget --quiet --output-document=flutter.tar.xz https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_v${FLUTTER_VERSION}.tar.xz && tar xf flutter.tar.xz > /dev/null && rm flutter.tar.xz
        - export PATH="$PATH":"$PWD/.pub-cache/bin"
        - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH

      script:
        - flutter doctor -v
        #- flutter build appbundle
        - cd android
        - bundle exec fastlane beta
