   stage: deploy
    name: "Deploy Android"
    os: linux
    dist: xenial
    addons:
    apt:
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
    before_install:
      - openssl aes-256-cbc -K $encrypted_885114b78094_key -iv $encrypted_885114b78094_iv -in secrets.tar.enc -out secrets.tar -d
      - tar xvf secrets.tar
      - gem update --system
      - gem install bundler -v 1.17.3
    before_script:
        - sh bin/clone-flutter-if-not-exists.sh
        - ./flutter/bin/flutter doctorlanguage: android
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
    android:
    components:
        - tools
        - platform-tools

      # The BuildTools version used by your project

          - build-tools-28.0.3

      # The SDK version used to compile your project

          - android-28
          - add-on
          - extrajdk: oraclejdk8
    script:
      - source bin/env.sh
      - ./flutter/bin/flutter build apk --flavor $APP_FLAVOR --release --build-number $TRAVIS_BUILD_NUMBER -t $APP_ENTRY
      - cd android/
      - bundle update
      - bundle exec fastlane beta