jobs:
  include:
    # start android beta
    - stage: Start Beta

      language: android
      before_install:
        - ANDROID_COMPILE_SDK=28
        - ANDROID_BUILD_TOOLS=28.0.1
        - ANDROID_SDK_TOOLS=4333796

        # Install android tools
        - export ANDROID_HOME=$HOME/android-sdk-linux
        - wget -q https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_SDK_TOOLS.zip -O android-sdk-tools.zip
        - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
        - rm android-sdk-tools.zip
        - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
        # Silence warning.
        - mkdir -p ~/.android
        - touch ~/.android/repositories.cfg
        # install correct version of java on osx (for sdkmanager to run)
        #        - brew cask uninstall java; brew tap caskroom/versions; brew cask install java8;
        # Accept licenses before installing components
        #- yes | sdkmanager --licenses
        # Platform tools
        - yes | sdkmanager "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
        - sdkmanager --list | head -15

      install:
        - sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null

        # install version of fastlane from Gemfile.lock
        - bundle install > /dev/null

        # install flutter
        - FLUTTER_CHANNEL=stable
        - FLUTTER_VERSION=1.0.0-${FLUTTER_CHANNEL}
        - wget --quiet --output-document=flutter.tar.xz https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_v${FLUTTER_VERSION}.tar.xz && tar xf flutter.tar.xz > /dev/null && rm flutter.tar.xz
        - export PATH="$PATH":"$PWD/.pub-cache/bin"
        - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor -v

      script:
        - (cd android && openssl enc -aes-256-cbc -d -in key.properties.enc -out key.properties -k $KEY_PASSWORD && openssl enc -aes-256-cbc -d -in key.jks.enc -out key.jks -k $KEY_PASSWORD && bundle exec fastlane beta)
        - flutter doctor -v
        - flutter build appbundle
        - cd android
        - bundle exec fastlane beta
