language: generic

# For now, Flutter doesn't provide a canonical way to define variables at build time
# https://github.com/flutter/flutter/issues/26638

env:
  # Fastlane 세팅 중 Play Store Console에 실수로 이 버전 코드를 갖는 apk를 업로드 했는데
  # 업로드한 apk를 삭제할 수단이 없어서 이 값을 버전 코드의 베이스로 사용한다.
  - VERSION_CODE_BASE=1908191509 FLUTTER_BUILD_RELEASE_CHANNEL=beta

branches:
  only:
    - master

matrix:
  include:
    - name: Android Build
      language: android
      jdk: openjdk8

      before_script:
        #- openssl aes-256-cbc -K $encrypted_d0cc22ff5b43_key -iv $encrypted_d0cc22ff5b43_iv -in secrets.tar.enc -out secrets.tar -d
        #- tar xvf secrets.tar
        - ANDROID_COMPILE_SDK=28
        - ANDROID_BUILD_TOOLS=28.0.1
        - ANDROID_SDK_TOOLS=4333796
        # Install android tools
        - export ANDROID_HOME=$HOME/android-sdk-linux
        - wget -q https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_SDK_TOOLS.zip -O android-sdk-tools.zip
        - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
        - rm android-sdk-tools.zip
        - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
        # Silence warning.
        - mkdir -p ~/.android
        - touch ~/.android/repositories.cfg
        - gem install bundler && cd android && bundle install && cd ..
      script:
        - flutter doctor -v
        - flutter build appbundle --build-number=$(( $VERSION_CODE_BASE + $TRAVIS_BUILD_NUMBER ))
        - cd android
        - bundle exec fastlane beta
