os: linux
language: android
# android 相关环境
android:
  components:
    - build-tools-28.0.3
    - android-28
jdk: oraclejdk8
sudo: false
# 运行 ci 的 docker 容器
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
# flutter doctor --android-licenses 要求先运行下面这条语句， yes | 表示后面的命令如果需要你输入 y/n 会自动帮你输入 y
before_install:
  - yes | sdkmanager --update
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH="$PATH:`pwd`/flutter/bin"
script:
  - flutter packages get
  # 由于用的新的 android , 需要接受额外的一些证书
  #- yes | flutter doctor --android-licenses
  - flutter -v build appbundle
# 缓存
cache:
  directories:
    - "$HOME/.pub-cache"