language: android
os:
  - linux

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - git clone -b beta --depth=1 https://github.com/flutter/flutter.git

install:
  - export PATH=./flutter/bin:$PATH

script:
  - flutter build aot
  - flutter build apk