# CONFIGURAÇÂO DO FASTLANE PARA DEPLOY NO GOOGLE PLAY
# update_fastlane

default_platform(:android)

platform :android do
  desc "ENVIANDO VERSAO BETA - GOOGLE PLAY"
  lane :beta do
    begin
      upload_to_play_store(
        track: 'beta',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        #apk: '../build/app/outputs/apk/release/app-release.apk',
      )
      rescue => exception
        raise exception unless exception.message.include?('apkUpgradeVersionConflict')
        puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end

  desc "DEPLOY NOVA VERSAO - GOOGLE PLAY"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
